service: node-set-service

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1

package:
  include:
    - env.json

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4040

functions:
  search:
    handler: src/handler.searchHandler
    events:
      - http:
          path: api/search
          method: get
          cors: true
